version: "3.8"

services:

  rabbitMQ:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${PROJECT_NAME:-default}-rabbitMQ
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq}
      TZ: Asia/Tokyo
    volumes:
      - hclabo_rabbitmq_volume:/var/lib/rabbitmq
      - ${PATH_LOG_RABBITMQ:-./docker/rabbitmq/rabbitmq_log}:/var/log/rabbitmq

  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: ${PROJECT_NAME:-default}-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: hclabo_order,hclabo_shop_management,hclabo_promotion,hclabo_payment,hclabo_logistic,hclabo_price_planning,hclabo_product,hclabo_user,hclabo_customize
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Tokyo
    volumes:
      - hclabo_postgres_volume:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
      - ${PATH_LOG_POSTGRES:-./docker/postgres/postgres_log}:/var/log/pgsql
      - ./docker/postgres/dump_data:/tmp/dump_data

  mongodb:
    image: ${PROJECT_NAME:-default}-mongodb
    container_name: ${PROJECT_NAME:-default}-mongodb
    build:
      context: ./docker/mongodb
      args:
        mongodb_version: ${MONGODB_VERSION}
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: hclabo_analytics
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_USER: ${MONGO_INITDB_USER:-hclabo_analytics}
      MONGO_INITDB_PWD: ${MONGO_INITDB_PWD:-password}
      MONGO_HOST: 127.0.0.1
      TZ: Asia/Tokyo
    volumes:
      - hclabo_mongodb_volume:/data/db
      - ./docker/mongodb/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mongodb/dump_data:/tmp/dump_data

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    container_name: ${PROJECT_NAME:-default}-mongo-express
    restart: unless-stopped
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      TZ: Asia/Tokyo
    depends_on:
      - mongodb

  fluentd:
    image: ${PROJECT_NAME:-default}-fluentd
    container_name: ${PROJECT_NAME:-default}-fluentd
    build:
      context: ./docker/fluentd
      args:
        fluent_version: ${FLUENTD_VERSION}
    restart: unless-stopped
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./docker/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/product:/home/hclabo/log/services/product
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/logistic:/home/hclabo/log/services/logistic
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/payment:/home/hclabo/log/services/payment
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/price-planning:/home/hclabo/log/services/price-planning
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/promotion:/home/hclabo/log/services/promotion
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/order:/home/hclabo/log/services/order
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/analytics:/home/hclabo/log/services/analytics
      - ${PATH_LOG_FLUENTD:-/home/hclabo/log/services}/customize:/home/hclabo/log/services/customize
    links:
      - mongodb

  zipkin:
    image: openzipkin/zipkin:${ZIPKIN_VERSION}
    container_name: ${PROJECT_NAME:-default}-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"

  nginx:
    image: ${PROJECT_NAME:-default}-nginx
    container_name: ${PROJECT_NAME:-default}-nginx
    build:
      context: ./docker/nginx
      args:
        nginx_version: ${NGINX_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${PATH_DOC_ROOT:-C:/var/home/hclabo/public_html}:/home/hclabo/public_html/
      - ${PATH_LOG_NGINX:-./docker/nginx/log}:/home/hclabo/log/middleware/nginx/
    extra_hosts:
      - host.ip:${HOST_IP}

  haproxy:
    image: haproxy:${HAPROXY_VERSION}
    container_name: ${PROJECT_NAME:-default}-haproxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "18080:18080"
      - "60001:60001"
      - "60002:60002"
      - "60003:60003"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./docker/haproxy/localhost.pem:/usr/local/etc/haproxy/localhost.pem
    extra_hosts:
      - host.docker.internal:host-gateway
      - host.ip:${HOST_IP}
    depends_on:
      - nginx

volumes:
  hclabo_postgres_volume:
  hclabo_rabbitmq_volume:
  hclabo_mongodb_volume:
