---
- hosts: torrington # Inventoryとして定義されたリモートホスト（torringtonサーバ）
  vars:
    ansible_become: yes
    ansible_become_method: sudo

  tasks:
    - name: hclabo-user-service-jar-copy
      copy:
        src: ../../target/hclabo-user-service-4.0.0-SNAPSHOT.jar
        dest: /data/hitmall/hclabo/services/user
        mode: '0755'
    - name: dockerfile-copy
      copy:
        src: ../Dockerfile
        dest: /data/hitmall/hclabo/services/user
        mode: '0755'
    - name: start-shell-copy
      copy:
        src: ../start.sh
        dest: /data/hitmall/hclabo/services/user
        mode: '0755'
    - name: env-file-copy
      copy:
        src: ../.env
        dest: /data/hitmall/hclabo/services/user
        mode: '0755'
    - name: hclabo-user-service-start
      shell: ./start.sh .env
      args:
        chdir: /data/hitmall/hclabo/services/user
    - name: unused-docker-images-delete
      shell: |
        docker system prune -a -f
        docker system prune --volumes -f
      args:
        chdir: /data/hitmall/hclabo/services/user
